### ISSUE TITLE
Extended Attributes in the Base/Default section are not available in the Extended Attributes tab/page 

### ISSUE THREAD

**Issue by tsucaet** [MasaCMS/MasaCMS#159] opened 2023-01-19 20:00 UTC
The Extended Attributes of a Class Extensions that resides in the Base/Default section are not available for any content type (Page, Folder,...)

For example, the Masa Google Sitemap plugins creates a 'Google Sitemaps' Class Extension in the Base/Default section with some attributes related to the settings of the Google Sitemap but are not available in the Extended Attributes tab/page in the content editor.

<img width="1281" alt="Schermafbeelding 2023-01-19 om 20 58 48" src="https://user-images.githubusercontent.com/778718/213546991-e897cf93-74f1-4f90-9937-0b1e835f8180.png">

**Comment by OriCat101** [comment] 2023-06-26 12:55
I'm having the same issue and upon comparing the two links in VScode the difference seems to be in the attribute name of the parent id, or more specifically between the t and i.

<img width="567" alt="image" src="https://github.com/MasaCMS/MasaCMS/assets/63188591/4e18d7b7-4edb-4f53-b5ad-0cae02c97bd1">

<img width="584" alt="image" src="https://github.com/MasaCMS/MasaCMS/assets/63188591/a0a2dabb-f91c-4b46-8d1e-8d3ec9d3caba">

**Comment by guustnieuwenhuis** [comment] 2023-07-05 14:56
duplicate of #209

**Closed by guustnieuwenhuis** 2023-07-05 14:56 UTC
Labels: bug, origin: masa support
