### ISSUE TITLE
File Manager Requires a Page Refresh to see any updates made

### ISSUE THREAD

**Issue by mikechy** [MasaCMS/MasaCMS#335] opened 2024-09-05 15:52 UTC
Any time a file is uploaded or re-named, you have to refresh the browser to see the  updates.

**To Reproduce**
Upload or Rename a file

**Expected behavior**
You should see the updates immediately

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Server 2022, OXS, Windows 10,11
 - Browser Chrome, Firefox, Safari

**Environment (please complete the following information):**
 - windows Server 2022
 - Lucee 5.4.6.9
 - SQL Server 2019
 - Masa 7.4.6

**Comment by jeroenweareorangeeu** [comment] 2024-09-12 11:24
Hi @mikechy 

I've tried to reproduce this, but I dont have the same problem.
When uploading / renaming files the filebrowser is supposed do a refresh. This works for me.

Can you check the console of your browser for any errors? 
In which language are you using Masa Admin? If not English, can you try logging in Masa CMS Admin using the English language? And try again?

![image](https://github.com/user-attachments/assets/30281d3e-c8db-438c-a50c-650ed19e7c15)



If the error persists provide steps to reproduce. 

Many thanks and greetings,

Jeroen

**Comment by mikechy** [comment] 2024-09-12 15:05
Thanks for the reply.  


it would seem that the page cache is the issue. If I go into developer tools (Chrome) and disable caching, it works as intended.  This also is the same fix for Firefox. If you disable page caching, it works.

 

Mike

**Comment by mikechy** [comment] 2024-09-12 19:34
Hello Jeroen.

 

We found it.  After that last test, we started to look at the “browse” call that is made after the upload or delete. 

 

A recent change was made to our .htaccess file that had this file altered:

 

ExpiresByType application/json A0

 

The expiration time was set to A31536000 which told the browser to cache JSON files.

 

Thanks for the reply, you can consider this closed.

 

Mike

**Comment by jeroenweareorangeeu** [comment] 2024-09-13 06:52
@mikechy  After reading your first comment, I had the impression it had something to do with the configuration of your webserver. Glad you found it. Will close this issue.

**Closed by jeroenweareorangeeu** 2024-09-13 06:52 UTC
Labels: bug, missing steps to reproduce
