### ISSUE TITLE
File Manager does not work

### ISSUE THREAD

**Issue by WaleedEhsan** [MasaCMS/MasaCMS#86] opened 2022-05-16 06:45 UTC
I installed the MasaCMS, and go to the File Manager the page not load even no error there 
![image](https://user-images.githubusercontent.com/16976475/168534494-bb24bcfc-513c-47b9-b3c5-47273592185e.png)

Please fix it.

**Comment by sejourla** [comment] 2022-05-16 08:03
Could you please expand the error in the console so we can see the entire message. Thank you!

**Comment by WaleedEhsan** [comment] 2022-05-16 08:08
![image](https://user-images.githubusercontent.com/16976475/168547768-c571ff19-e317-4372-92ea-060416cebb1c.png)

**Comment by sejourla** [comment] 2022-05-16 09:40
I need you to click on the right-facing triangle beside the red circle, to expand the error. The image you attached provides no information on the error itself.
![clickhere](https://user-images.githubusercontent.com/81464587/168564644-b4bbe97c-a581-4607-94b6-c49ce9b91375.png)

**Comment by sejourla** [comment] 2022-05-16 11:41
I noticed you have Masa installed in a sub-directory ... can you check to make sure the context value in the /core/settings.ini.cfm matches this, i.e.:

context=/MuraCMS

**Comment by WaleedEhsan** [comment] 2022-05-16 12:08
I see it is there context=/MasaCMS
do you need me to change it to MuraCMS really?

**Comment by AlHolden** [comment] 2022-05-16 15:40
In my original discussion [here](https://github.com/MasaCMS/MasaCMS/discussions/83#discussioncomment-2757170), I was making the assumption that an Amazon S3 configuration had something to do with the problem (that the File Browser is not showing any assets, but all the sites are showing them just fine).

Waleed is getting a 404 in his off-the-shelf installation, perhaps due to a config or mapping issue.

Please note that I am NOT getting any console or network errors in my environment. I presume the File Browser is simply not showing any of the "User Assets" files, because it is looking in the wrong place. If I knew from what config setting or lines of code (where the FB is setting something different from the front end), then I could tinker with that. Maybe the FB needs its' own dedicated path setting to prepend or append?

**Comment by sejourla** [comment] 2022-05-16 16:43
@AlHolden ... as you said, it is a 404 issue, which does lean towards configuration/mapping. 

Hi @WaleedEhsan ... no, that was a misprint .... context=/MasaCMS is correct. Do you have a site with a siteid of "MasaCMS" set up? If so, you will need to delete that.

Also, does the base API url (http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/) work for you, or does it also return an error?

**Comment by WaleedEhsan** [comment] 2022-05-16 17:09
@sejourla My site name is the default.
When I hit the API directly, the following is the response.
`{
	"data": {
		"endindex": 13,
		"startindex": 1,
		"entityname": "entity",
		"totalpages": 1,
		"totalitems": 13,
		"links": {
			"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/entity/permissions",
			"entities": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default",
			"self": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/?&entityname=entity&siteid=default&method=findall&pageIndex=1",
			"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/entity/properties"
		},
		"itemsperpage": 1000,
		"items": [{
			"entityname": "address",
			"displayname": "address",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/address",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/address/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/address/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "category",
			"displayname": "category",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/category",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/category/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/category/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "changeset",
			"displayname": "changeset",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/changeset",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/changeset/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/changeset/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "changesetCategoryAssignment",
			"displayname": "changesetCategoryAssignment",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/changesetCategoryAssignment",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/changesetCategoryAssignment/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/changesetCategoryAssignment/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "comment",
			"displayname": "comment",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/comment",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/comment/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/comment/properties"
			},
			"orderby": "entered asc",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "content",
			"displayname": "content",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/content",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/content/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/content/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "contentCategoryAssign",
			"displayname": "contentCategoryAssign",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/contentCategoryAssign",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/contentCategoryAssign/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/contentCategoryAssign/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "file",
			"displayname": "file",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/file",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/file/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/file/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "fileMetaData",
			"displayname": "fileMetaData",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/fileMetaData",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/fileMetaData/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/fileMetaData/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "group",
			"displayname": "group",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/group",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/group/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/group/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "site",
			"displayname": "site",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/site",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/site/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/site/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "stats",
			"displayname": "stats",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/stats",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/stats/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/stats/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}, {
			"entityname": "user",
			"displayname": "user",
			"links": {
				"endpoint": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/user",
				"permissions": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/user/permissions",
				"properties": "http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/user/properties"
			},
			"orderby": "",
			"scaffold": false,
			"dynamic": false
		}],
		"pageindex": 1
	},
	"method": "findAll",
	"apiversion": "v1"
}`

**Comment by AlHolden** [comment] 2022-05-16 18:58
Thanks @sejourla 
But just to be clear, _Waleed's environment_ displays a 404.
In my OP (after which I asked for his help) _my environment_ displays NO ERRORS at all. No network 404, no console error. 
The FB performed a complete and error-free task, while likely looking in the wrong place and therefore listing no contents in the resulting UI.

**Comment by sejourla** [comment] 2022-05-17 08:51
What do you see if you navigate directly to http://localhost:8888/MasaCMS/index.cfm/_api/json/v1/default/filebrowser/browse ?

**Comment by WaleedEhsan** [comment] 2022-05-17 09:12
Error 404
![image](https://user-images.githubusercontent.com/16976475/168775391-0e8da3c2-2fdf-46f3-a404-22300125e27f.png)

**Comment by sejourla** [comment] 2022-05-17 09:33
Also, how are you running Masa? Are you using the docker container, or have you set up your environment manually?

**Comment by sejourla** [comment] 2022-05-17 09:54
For what it is worth, I have just set up a new instance of Masa using the /core/docker/local-mysql/ compose file, running Masa within a /masacms context, and there were no issues with Filemanager:
![Screen Shot 2022-05-17 at 11 48 19 AM](https://user-images.githubusercontent.com/81464587/168784038-3f30f71c-53e8-477d-9dac-1365a64bcbcc.png)

**Comment by WaleedEhsan** [comment] 2022-05-17 10:31
I try app reload. not work.
There is no folder in the root with the name app.
I am running version Lucee 5.3.8.206.
I get the latest copy from the git and try not to work. This time error is 
![image](https://user-images.githubusercontent.com/16976475/168791309-724dd8fb-920b-465b-983b-966bc057a9dc.png)
![image](https://user-images.githubusercontent.com/16976475/168791485-78efd1df-d3f0-4ef0-bc86-2d41f274e094.png)
---------------------

Anyways I am now going to try with command box. Let c.

**Comment by WaleedEhsan** [comment] 2022-05-17 10:45
It is when I try a fresh instance with command box
![image](https://user-images.githubusercontent.com/16976475/168793953-96ebd320-f83c-4790-b243-3e9e8c1046b5.png)

**Comment by sejourla** [comment] 2022-05-17 11:17
The last error is a CORS issue, because you've got localhost as the source but the request is going to 127.0.0.1. In site settings, make sure "localhost" is entered as your primary domain.

**Comment by WaleedEhsan** [comment] 2022-05-17 11:29
yay! It works 
![image](https://user-images.githubusercontent.com/16976475/168800810-7eeca3f8-e9cc-4c8e-9ad5-5590fbe20f54.png)
@sejourla now how to fix it on our server that is running lucee (not commandbox)?

**Comment by sejourla** [comment] 2022-05-17 12:20
I would suggest reviewing your lucee logs ... it could be either a permission or mapping issue.

**Comment by WaleedEhsan** [comment] 2022-05-17 12:44
Below are the logs. Please have a look and help.
------------------------------ Application.log----------------------
`"Severity","ThreadID","Date","Time","Application","Message"
"ERROR","127.0.0.1-startStop-1","05/17/2022","17:36:29","OSGi","Given version [${version}] is invalid, a valid version is following this pattern <major-number>.<minor-number>.<micro-number>[.<qualifier>];Given version [${version}] is invalid, a valid version is following this pattern <major-number>.<minor-number>.<micro-number>[.<qualifier>];org.osgi.framework.BundleException: Given version [${version}] is invalid, a valid version is following this pattern <major-number>.<minor-number>.<micro-number>[.<qualifier>]
	at lucee.runtime.osgi.OSGiUtil.toVersion(OSGiUtil.java:250)
	at lucee.runtime.osgi.BundleInfo.<init>(BundleInfo.java:102)
	at lucee.runtime.osgi.BundleFile.<init>(BundleFile.java:62)
	at lucee.runtime.osgi.BundleFile.getInstance(BundleFile.java:55)
	at lucee.runtime.osgi.BundleFile.getInstance(BundleFile.java:42)
	at lucee.runtime.config.ConfigWebUtil.loadLib(ConfigWebUtil.java:201)
	at lucee.runtime.config.XMLConfigWebFactory.load(XMLConfigWebFactory.java:444)
	at lucee.runtime.config.XMLConfigWebFactory.newInstance(XMLConfigWebFactory.java:282)
	at lucee.runtime.engine.CFMLEngineImpl.loadJSPFactory(CFMLEngineImpl.java:908)
	at lucee.runtime.engine.CFMLEngineImpl.addServletConfig(CFMLEngineImpl.java:781)
	at lucee.loader.engine.CFMLEngineWrapper.addServletConfig(CFMLEngineWrapper.java:88)
	at lucee.loader.engine.CFMLEngineFactory.getInstance(CFMLEngineFactory.java:176)
	at lucee.loader.engine.CFMLEngineFactory.getInstance(CFMLEngineFactory.java:213)
	at lucee.loader.servlet.CFMLServlet.init(CFMLServlet.java:42)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1144)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1878)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"
"ERROR","Thread-9","05/17/2022","17:37:00","lucee.runtime.net.smtp.SMTPClient","timeout occurred after 30 seconds while sending mail message;timeout occurred after 30 seconds while sending mail message;javax.mail.MessagingException: timeout occurred after 30 seconds while sending mail message
	at lucee.runtime.net.smtp.SMTPClient._send(SMTPClient.java:881)
	at lucee.runtime.spooler.mail.MailSpoolerTask.execute(MailSpoolerTask.java:125)
	at lucee.runtime.spooler.SpoolerTaskSupport._execute(SpoolerTaskSupport.java:107)
	at lucee.runtime.spooler.SpoolerEngineImpl.execute(SpoolerEngineImpl.java:595)
	at lucee.runtime.spooler.SpoolerEngineImpl$TaskThread.run(SpoolerEngineImpl.java:533)
"`

-------------------------------- deprecations.log  ---------------------
`"Severity","ThreadID","Date","Time","Application","Message"
"INFO","http-nio-8888-exec-7","05/17/2022","17:37:48","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-8","05/17/2022","17:37:48","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-5","05/17/2022","17:37:55","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-2","05/17/2022","17:37:56","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-6","05/17/2022","17:37:56","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-4","05/17/2022","17:37:58","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-5","05/17/2022","17:37:58","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"
"INFO","http-nio-8888-exec-10","05/17/2022","17:38:07","","Deprecation warning: MuraScopeObject: The MuraScope.cfc object has been initialized. This will be replaced by the MasaScope.cfc object. 

Linenumber: 17: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\modules\v1\deprecation\model\handlers\handler.cfc: Function: onLogDeprecation

Linenumber: 1770: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: executeScripts

Linenumber: 1760: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1615: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: announceEvent

Linenumber: 1307: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\plugin\pluginManager.cfc: Function: init

Linenumber: 401: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MasaScope.cfc: Function: resolveBeanCreate

Linenumber: 86: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\MuraScope.cfc: Function: resolveBean

Linenumber: 740: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: getBean

Linenumber: 620: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequest

Linenumber: 132: Template: C:\lucee\tomcat\webapps\ROOT\MasaCMS\core\mura\bean\ioc.cfc: Function: setupRequestWrapper"`

**Comment by grantshepert** [comment] 2022-05-23 14:18
We are looking into a few issues with s3 and the file browser; will post an update once these are complete.

**Comment by pauaware** [comment] 2022-06-21 10:50
Hi there, if I turn off 'Use SSL Sitewide' in the Site Settings my FileBrowser works. If I turn it on it fails (blank console, no errors) ... hoping this provides a clue to what's happening with the file access/visibility

**Comment by grantshepert** [comment] 2022-06-21 11:49
@pauaware do you have a value set for "Primary Domain" in site settings? Setting this might also resolve the issue (it might be caused by an incorrect url for the dynamically-loaded Vue files).

**Comment by AlHolden** [comment] 2022-06-22 17:03
This note is regarding my [May 17 comment](https://github.com/MasaCMS/MasaCMS/issues/86#issuecomment-1129129575) earlier.
@pauaware - but the site is already set with  _'Use SSL Sitewide'_ turned off.
@grantshepert - this site _does_ have a Primary Domain set.
My related issue is [here](https://github.com/MasaCMS/MasaCMS/discussions/83), and apparently has something to do with S3

**Comment by jeroenweareorangeeu** [comment] 2024-09-12 11:13
Hello @WaleedEhsan,

Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by pauaware** [comment] 2024-09-13 00:57
Hi Jeroen,

All sorted, seems to have been corrected in subsequent releases.

Kind regards,

Matt

**Comment by jeroenweareorangeeu** [comment] 2024-09-13 06:51
Great to hear @pauaware, I will close this ticket.

**Closed by jeroenweareorangeeu** 2024-09-13 06:51 UTC
Labels: bug, origin: community
