### ISSUE TITLE
Could not view Form data when not using USA formats.

### ISSUE THREAD

**Issue by OriCat101** [MasaCMS/MasaCMS#302] opened 2024-04-02 07:05 UTC
**Describe the bug**
Could not view Form data when not using USA formats.

**To Reproduce**
1. Go to masa admin
2. Click on forms
3. Select a form with data
4. go to form data
5. Set a time period
6. See error

**Expected behavior**
It should just open a page where you can view all the form data.

**Screenshots**
5. <img width="447" alt="image" src="https://github.com/MasaCMS/MasaCMS/assets/63188591/d841e021-0be5-4ff5-af69-942dee9cc2be">
6. <img width="584" alt="image" src="https://github.com/MasaCMS/MasaCMS/assets/63188591/b79d1234-6eaf-401e-a23c-f17e2597e3e7">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Arc (chromium based)

**Environment (please complete the following information):**
 - OS: Windows
 - CFML Engine: Lucee 5.4
 - Database MSSQL

**Additional context**
With the code changes in [PR#299](https://github.com/MasaCMS/MasaCMS/pull/299) it totally works

**Comment by jeroenweareorangeeu** [comment] 2024-04-04 11:28
Hello,

Thank you for your elaborate report and steps to reproduce.
I'v tried to reproduce this error, but I can't seem to find an error. Tested on Masa 7.4.6.
I've tried this with Lucee and MySQL, and also CF and MSSQL, but could not find anything wrong.

Does this error apppears ALWAYS, or just when filtering on certain dates?

I tried if perhaps the locale of the site was an issue, because by the name of the form the site might be in German, but this wasnt the case. It appears that your Locale in Masa is 'en_us' right?

Perhaps there is something in the Form itself? Can you provide more information? How is this constructed? Which inputs are you using? What is the config of the form (validation, requirement)?
Are there any errors / warnings on your browser console?

Another hint is that the error Alert says:

'The 'to' field must a valid date'
'The 'to' field must a valid date'

This error message is somewhat misleading, because both date fields have the same error message, but it implies there is an error with BOTH fields.

Thats it for now. I hope these hints help. Looking forward to your reply.

**Comment by OriCat101** [comment] 2024-04-04 12:23
Hiiii

> I tried if perhaps the locale of the site was an issue, because by the name of the form the site might be in German, but this wasnt the case. It appears that your Locale in Masa is 'en_us' right?

The site locale is set to de_ch, and this seems to be part of the issue.

> Does this error apppears ALWAYS, or just when filtering on certain dates?

The error always, even if I choose a date like `03.03.yyyy` which should work both ways

> Perhaps there is something in the Form itself?

I don't think it is since I can download the data just fine and if I implement the changes in the PR it also works just fine.

> Which inputs are you using? What is the config of the form (validation, requirement)?

I've tried it with a dummy form that just had one text input (nothing else), with no validation, and the error still occurs

**Comment by jeroenweareorangeeu** [comment] 2024-04-04 12:51
Just a quick question: how did you set your Locale to 'de_ch'? In the settings.ini.cfm file? Of in the site itself?

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/8de6965d-bbc5-4ea8-866b-12fc8078a0b7)

Or otherwise perhaps? Let me know please, so I can try to reproducer this error.

**Comment by OriCat101** [comment] 2024-04-04 12:55
The locale is set on the server and not on the site itself
![image](https://github.com/MasaCMS/MasaCMS/assets/63188591/8ff88fea-495a-403c-9257-559f7884310a)

**Comment by jeroenweareorangeeu** [comment] 2024-04-11 14:02
Hello,

One thing I noticed, when I set the locale in Masa in the Site Settings:

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/17f8c52e-a0c3-45ef-933f-6ab5c71b53db)

(fair warning; changeing the locale on you production site, might have impact on how it is displayed)

Then the Date Selectors look like this:

![image](https://github.com/MasaCMS/MasaCMS/assets/83004496/9dd7d6e2-3757-4cd7-8e42-d348a2578b64)

The Date Selectors appear to be in a 'German' formatting; then abbreviations for the months are in German.
This differs from the screenshot you provided, which appear to be still having the 'en_us' formatting.
This implies that the locale that is set on your Server is still 'en_us' or this setting doesnt fall through into Masa.
Might be worth looking into.

Also you can perhaps try another browser like Chrome and/or Firefox and see if that works better.

**Comment by OriCat101** [comment] 2024-04-11 14:07
Different browsers were the first thing I tried.
And I also confirmed that the server is indeed set to german. So my guess is that it doesn't fully follow through to Masa.
But thx for the fix, I'll make sure to set the locale in Masa on Monday and see if it works.

I will keep you posted.

**Comment by OriCat101** [comment] 2024-05-03 13:40
Okay so, I think I've found the issue. 

The masa locale dropdown was set to:
<img width="948" alt="image" src="https://github.com/MasaCMS/MasaCMS/assets/63188591/64b89fca-19d6-4a58-8f01-b8ebf0543141">

and then I get the error described in the Initial post.
However, if I set it to 
<img width="943" alt="image" src="https://github.com/MasaCMS/MasaCMS/assets/63188591/eb0b513f-f183-47ab-918c-21348fb54b4d">

It works fine.

Soooo... ig the issue is the Locale?

**Comment by jeroenweareorangeeu** [comment] 2024-05-16 08:43
Hello,

That's great news! Thanks for the update. :-)
I have checked the DataManager with the 'swiss german (switzerland)' locale on my local enviroment and I can confirm that I get the same error as you posted before. (Hooray! I can now reproduce this bug.)

I will look into fixing this issues. 
For the mean time, I hope that the other locale 'german (switzerland)' is a suitable workaround for you for now.

**Comment by jeroenweareorangeeu** [comment] 2024-06-04 11:47
@OriCat101 

You can check this (simple) PR I've made for supporting the 'swiss german (switzerland)' locale.
https://github.com/MasaCMS/MasaCMS/pull/312

**Comment by OriCat101** [comment] 2024-06-10 13:54
thx <3
 So should I wait till the merge or close the issue now?

**Comment by jeroenweareorangeeu** [comment] 2024-06-10 14:11
Hi,

So I gather that you like this simple fix and that it also works.
If so, then it will be part of the next release. Please let me know.
At this time it is not know yet when we will create a new Masa release, but I hope 'soon'.

This also means that we will not accept the PR you created yourself, sorry.
https://github.com/MasaCMS/MasaCMS/pull/299
This is because the real problem was the missing language switch.

I would like to thank you for all your time and effort working with me on finding and solving this very interesting bug.
This will make Masa CMS even better! 

I would suggest keeping this ticket open, until the new release, after which we will close it.

Kind regards,

Jeroen

**Closed** 2024-06-21 12:15 UTC
Labels: bug
